module.exports = [
    { code: "525", error: "Unable to find user account details" },
    { code: "52e", error: "Invalid Microsoft account credentials" },
    { code: "530", error: "Your are not permitted to logon at this time" },
    { code: "531", error: "Your are not permitted to logon from this workstation" },
    { code: "532", error: "Your Microsoft account password expired" },
    { code: "533", error: "Your Microsoft account is disabled" },
    { code: "701", error: "Your Microsoft account is expired" },
    { code: "773", error: "You have to reset your Microsoft password" },
    { code: "775", error: "Your Microsoft account is locked out" },
    { code: "776", error: "Your Microsoft account is not activated" },
    { code: "777", error: "Your Microsoft account is not registered" },
    { code: "778", error: "Your Microsoft account is not valid" },
    { code: "getaddrinfo ENOTFOUND coldc01brandixlkorg", error: "connection to active directory failed" },
];